import React from 'react'
import NavbarProject from './PageComponents/NavbarProject'
import Porfolio from './PageComponents/Porfolio'
import Footer from '../Footer'
import imgUrl from '../../imgUrl.json';


export default function VillaFlorence() {

  const data = [
    {
      id:1,
      imgSrc:"img/portfolio/V01/global/06-large-global.JPG"
    },
    {
      id:2,
      imgSrc:"img/portfolio/V01/global/05-large-global.JPG"
    },
    {
      id:3,
      imgSrc:"img/portfolio/V01/global/04-large-global.avif"
    },
    {
      id:4,
      imgSrc:"img/portfolio/V01/global/03-large-global.JPG"
    },
    {
      id:5,
      imgSrc:"img/portfolio/V01/global/02-large-global.JPG"
    },
    {
      id:6,
      imgSrc:"img/portfolio/V01/global/01-large-global.JPG"
    },
    {
      id:7,
      imgSrc:"img/portfolio/V01/exterior/08-large-exterior.jpg"
    },
    {
      id:8,
      imgSrc:"img/portfolio/V01/exterior/07-large-exterior.jpg"
    },
    {
      id:9,
      imgSrc:"img/portfolio/V01/exterior/06-large-exterior.jpg"
    },
    {
      id:10,
      imgSrc:"img/portfolio/V01/exterior/04-large-exterior.jpg"
    },
    {
      id:11,
      imgSrc:"img/portfolio/V01/exterior/03-large-exterior.jpg"
    },
    {
      id:12,
      imgSrc:"img/portfolio/V01/exterior/02-large-exterior.jpg"
    },
    {
      id:13,
      imgSrc:"img/portfolio/V01/exterior/01-large-exterior.jpg"
    },
    {
      id:14,
      imgSrc:"img/portfolio/V01/baños/IMG_0785.jpg"
    },
    {
      id:15,
      imgSrc:"img/portfolio/V01/baños/IMG_0787.jpg"
    },
    {
      id:16,
      imgSrc:"img/portfolio/V01/baños/IMG_0788.jpg"
    },
    {
      id:17,
      imgSrc:"img/portfolio/V01/baños/IMG_0808.jpg"
    },
    {
      id:18,
      imgSrc:"img/portfolio/V01/baños/IMG_0816.jpg"
    },
    {
      id:19,
      imgSrc:"img/portfolio/V01/cocina/IMG_0802.jpg"
    },
    {
      id:20,
      imgSrc:"img/portfolio/V01/cocina/IMG_0824.jpg"
    },
    {
      id:21,
      imgSrc:"img/portfolio/V01/cocina/IMG_0833.jpg"
    },
    {
      id:22,
      imgSrc:"img/portfolio/V01/escaleras/01-large-escaleras.jpg"
    },
    {
      id:23,
      imgSrc:"img/portfolio/V01/interior/01-large-interior.jpg"
    },
    {
      id:24,
      imgSrc:"img/portfolio/V01/interior/02-large-interior.jpg"
    },
    {
      id:25,
      imgSrc:"img/portfolio/V01/interior/IMG_0782.jpg"
    },
    {
      id:26,
      imgSrc:"img/portfolio/V01/interior/IMG_0794.jpg"
    },
    {
      id:27,
      imgSrc:"img/portfolio/V01/interior/IMG_0798.jpg"
    },
    {
      id:28,
      imgSrc:"img/portfolio/V01/interior/IMG_0799.jpg"
    },
    {
      id:29,
      imgSrc:"img/portfolio/V01/interior/IMG_0800.jpg"
    },
    {
      id:30,
      imgSrc:"img/portfolio/V01/interior/IMG_0801.jpg"
    },
    {
      id:31,
      imgSrc:"../../img/portfolio/V01/interior/IMG_0803.jpg"
    },
    {
      id:32,
      imgSrc:"img/portfolio/V01/interior/IMG_0805.jpg"
    },
    {
      id:33,
      imgSrc:"img/portfolio/V01/interior/IMG_0809.jpg"
    },
    {
      id:34,
      imgSrc:"img/portfolio/V01/interior/IMG_0810.jpg"
    },
    {
      id:35,
      imgSrc:"img/portfolio/V01/interior/IMG_0811.jpg"
    },
    {
      id:36,
      imgSrc:"img/portfolio/V01/interior/IMG_0814.jpg"
    },
    {
      id:37,
      imgSrc:"img/portfolio/V01/interior/IMG_0817.jpg"
    },
    {
      id:38,
      imgSrc:"img/portfolio/V01/interior/IMG_0819.jpg"
    },
    {
      id:39,
      imgSrc:"img/portfolio/V01/interior/IMG_0822.jpg"
    },
    {
      id:40,
      imgSrc:"img/portfolio/V01/interior/IMG_0825.jpg"
    },
    {
      id:41,
      imgSrc:"img/portfolio/V01/interior/IMG_0827.jpg"
    },
    {
      id:42,
      imgSrc:"img/portfolio/V01/interior/IMG_0830.jpg"
    },
    {
      id:43,
      imgSrc:"img/portfolio/V01/interior/IMG_0832.jpg"
    },
    {
      id:44,
      imgSrc:"img/portfolio/V01/parking/01-large-parking.jpg"
    },
    {
      id:45,
      imgSrc:"img/portfolio/V01/parking/02-large-parking.jpg"
    },
    {
      id:46,
      imgSrc:"img/portfolio/V01/pool/01-large-pool.jpg"
    },
    {
      id:47,
      imgSrc:"img/portfolio/V01/pool/02-large-pool.jpg"
    },
    {
      id:48,
      imgSrc:"img/portfolio/V01/pool/03-large-pool.jpg"
    },
    {
      id:49,
      imgSrc:"img/portfolio/V01/pool/04-large-pool.jpg"
    },
    {
      id:50,
      imgSrc:"img/portfolio/V01/pool/05-large-pool.jpg"
    },
    {
      id:51,
      imgSrc:"img/portfolio/V01/pool/06-large-pool.jpg"
    },
  ]

  return (
    <div>
      <NavbarProject />
      <Porfolio 
        data = { imgUrl.villaFlorence }
        title = { "Villa Florence" }
        isGallery = {true}
        />
      <Footer />
    </div>
  )
}
